# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

## Check current Tcl, Tk version:
if {[package vcompare [package provide Tcl] 8.4] < 0} {
    return
}
if {[package provide Tk] == ""} {
    return
}
if {[regexp -nocase -- {cygwin} $::tcl_platform(os) ]} {
    # Don't load this dll into a cygwin Tcl - it'll crash.
    return
}

proc loadtkDnd {dir} {
    load [file join $dir libtkdnd10[info sharedlibextension]]
    #proc dnd {args} {}
    source [file join $dir tkdnd.tcl]
    package provide tkdnd 1.0
    rename loadtkDnd ""
}

package ifneeded tkdnd 1.0 [list loadtkDnd $dir]

