# Tcl package index file, version 1.1
# This file was generated by hand.
# 
# It invokes the "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically in response
# to "package require" commands.  When this script is sourced, the
# variable $dir must contain the full path name of this file's
# directory.

# Only declare the package if it is available for the current platform.
set file [file join $dir libtclparser14[info sharedlibextension]]
if {[file exists $file]} {
    package ifneeded parser 1.4 [list load $file Tclparser]
}
unset file

